#coding=utf-8

from django.core.management.base import BaseCommand, CommandError
from django.core.files import File
from xcards.cards.models import *
import os

class Command(BaseCommand):
	help = 'Import data from an xml file generated by gc-star'
	
	def handle(self, *args, **options):
		for item in Card.objects.all():
			print item.subcategory
			t1, created1 = Tag.objects.get_or_create(label=str(item.subcategory))
			t2, created2 = Tag.objects.get_or_create(label=str(item.subcategory.category))
			
			t1.save()
			t2.save()
			
			# add tags to item
			item.tags.add(t1)
			item.tags.add(t2)
			
			# save item
			item.save()
